package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func setEnv(t *testing.T, kv map[string]string) {
	t.Helper()
	for _, k := range []string{
		"ANTHROPIC_API_KEY", "SOUSCHEF_MODEL", "SOUSCHEF_EFFORT", "SOUSCHEF_DB_PATH",
		"SOUSCHEF_PORT", "TELEGRAM_BOT_TOKEN", "TELEGRAM_ALLOWED_CHAT_ID",
		"WHISPER_BIN", "WHISPER_MODEL", "AUDIO_DIR",
	} {
		os.Unsetenv(k)
	}
	for k, v := range kv {
		t.Setenv(k, v)
	}
}

// validEnv returns an environment that should load cleanly, with real files
// on disk for the whisper binary and model.
func validEnv(t *testing.T) map[string]string {
	t.Helper()
	dir := t.TempDir()
	bin := filepath.Join(dir, "whisper-cli")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	model := filepath.Join(dir, "ggml-base.en.bin")
	if err := os.WriteFile(model, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	return map[string]string{
		"ANTHROPIC_API_KEY":        "sk-ant-test",
		"SOUSCHEF_DB_PATH":         filepath.Join(dir, "test.db"),
		"TELEGRAM_BOT_TOKEN":       "123:abc",
		"TELEGRAM_ALLOWED_CHAT_ID": "42",
		"WHISPER_BIN":              bin,
		"WHISPER_MODEL":            model,
		"AUDIO_DIR":                filepath.Join(dir, "audio"),
	}
}

// writeDotEnv drops a .env file into a temp directory and chdirs there, so a
// test can exercise the setup the README actually documents: a file on disk
// and nothing in the ambient environment.
func writeDotEnv(t *testing.T, kv map[string]string) {
	t.Helper()

	var b strings.Builder
	b.WriteString("# generated by test\n")
	for k, v := range kv {
		b.WriteString(k)
		b.WriteString("=")
		b.WriteString(v)
		b.WriteString("\n")
	}

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(b.String()), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)
}

// The regression test for the bug that shipped: every verification run used
// inline environment variables, so the documented path — copy .env.example,
// fill it in, run the binary — was never once exercised, and nothing in the
// codebase actually read the file.
func TestLoadReadsDotEnvFile(t *testing.T) {
	env := validEnv(t)
	setEnv(t, nil) // nothing in the ambient environment
	writeDotEnv(t, env)

	cfg, err := Load()
	if err != nil {
		t.Fatalf("a .env file alone must be enough to start: %v", err)
	}
	if !cfg.LoadedDotEnv {
		t.Error("LoadedDotEnv should report that the file was used")
	}
	if cfg.TelegramToken != "123:abc" {
		t.Errorf("TelegramToken = %q, want it read from .env", cfg.TelegramToken)
	}
	if cfg.TelegramChatID != 42 {
		t.Errorf("TelegramChatID = %d, want 42 from .env", cfg.TelegramChatID)
	}
	if cfg.WhisperBin != env["WHISPER_BIN"] {
		t.Errorf("WhisperBin = %q, want %q", cfg.WhisperBin, env["WHISPER_BIN"])
	}
}

// A real environment variable must win over the file. This is what lets the
// Playwright config and any ad-hoc run override a developer's .env without
// editing it.
func TestRealEnvVarBeatsDotEnv(t *testing.T) {
	env := validEnv(t)
	fileEnv := make(map[string]string, len(env))
	for k, v := range env {
		fileEnv[k] = v
	}
	fileEnv["SOUSCHEF_PORT"] = "1111"
	fileEnv["TELEGRAM_ALLOWED_CHAT_ID"] = "1"

	setEnv(t, map[string]string{
		"SOUSCHEF_PORT":            "2222",
		"TELEGRAM_ALLOWED_CHAT_ID": "99",
	})
	writeDotEnv(t, fileEnv)

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Port != 2222 {
		t.Errorf("Port = %d, want 2222 — the ambient variable must beat .env", cfg.Port)
	}
	if cfg.TelegramChatID != 99 {
		t.Errorf("TelegramChatID = %d, want 99 — the ambient variable must beat .env", cfg.TelegramChatID)
	}
}

// Every automated run in this project supplies configuration inline. A missing
// .env must stay a non-event, not a startup failure.
func TestMissingDotEnvIsNotAnError(t *testing.T) {
	setEnv(t, validEnv(t))
	t.Chdir(t.TempDir()) // a directory with no .env in it

	cfg, err := Load()
	if err != nil {
		t.Fatalf("a missing .env must not be an error: %v", err)
	}
	if cfg.LoadedDotEnv {
		t.Error("LoadedDotEnv should be false when no file was found")
	}
}

// A malformed .env must fail loudly and name the file, rather than being
// silently skipped — a typo'd file that is quietly ignored strands you exactly
// as an unread one does.
//
// The input here is a line missing its "=", which is both the most likely
// hand-editing mistake and one godotenv genuinely rejects. Note it is NOT a
// full validator: a stray null byte mid-line, an empty key, or a key starting
// with a digit all parse without complaint. This test pins the boundary we
// actually get, not a guarantee of total validation.
func TestMalformedDotEnvIsReported(t *testing.T) {
	setEnv(t, nil)

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("SOUSCHEF_PORT 8420\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)

	_, err := Load()
	if err == nil {
		t.Fatal("expected an error for a malformed .env")
	}
	if !strings.Contains(err.Error(), ".env") {
		t.Errorf("error must name the file, got: %v", err)
	}
}

func TestLoadAppliesDefaults(t *testing.T) {
	setEnv(t, validEnv(t))
	cfg, err := Load()
	if err != nil {
		t.Fatalf("expected clean load, got %v", err)
	}
	if cfg.Model != "claude-sonnet-5" {
		t.Errorf("Model = %q, want claude-sonnet-5", cfg.Model)
	}
	if cfg.Effort != "low" {
		t.Errorf("Effort = %q, want low", cfg.Effort)
	}
	if cfg.Port != 8420 {
		t.Errorf("Port = %d, want 8420", cfg.Port)
	}
	if cfg.TelegramChatID != 42 {
		t.Errorf("TelegramChatID = %d, want 42", cfg.TelegramChatID)
	}
}

func TestLoadFailsOnMissingWhisperBinary(t *testing.T) {
	env := validEnv(t)
	env["WHISPER_BIN"] = "/nonexistent/whisper-cli"
	setEnv(t, env)

	_, err := Load()
	if err == nil {
		t.Fatal("expected error for missing whisper binary")
	}
	if !strings.Contains(err.Error(), "WHISPER_BIN") {
		t.Errorf("error must name the offending variable, got: %v", err)
	}
}

func TestLoadFailsOnMissingTelegramToken(t *testing.T) {
	env := validEnv(t)
	delete(env, "TELEGRAM_BOT_TOKEN")
	setEnv(t, env)

	_, err := Load()
	if err == nil {
		t.Fatal("expected error for missing telegram token")
	}
	if !strings.Contains(err.Error(), "TELEGRAM_BOT_TOKEN") {
		t.Errorf("error must name the offending variable, got: %v", err)
	}
}

func TestLoadFailsOnNonNumericChatID(t *testing.T) {
	env := validEnv(t)
	env["TELEGRAM_ALLOWED_CHAT_ID"] = "not-a-number"
	setEnv(t, env)

	if _, err := Load(); err == nil {
		t.Fatal("expected error for non-numeric chat id")
	}
}

func TestLoadCreatesAudioDir(t *testing.T) {
	env := validEnv(t)
	setEnv(t, env)

	cfg, err := Load()
	if err != nil {
		t.Fatalf("expected clean load, got %v", err)
	}
	info, err := os.Stat(cfg.AudioDir)
	if err != nil || !info.IsDir() {
		t.Errorf("AudioDir %q should exist as a directory", cfg.AudioDir)
	}
}
